highlight-font: '"GT Walsheim", "gt_walsheim_regular", "Avant Garde Gothic ITCW01Dm", "Avant Garde", "Helvetica Neue", "Arial'
body: '"Helvetica Neue", "Arial", san-serif'
code: '"Monaco", "Menlo", "Consolas", "Courier New", monospace'

highlight-color: "#00C8FF"
highlight-dark-color: "#00A0FF"
darker-color: "#999999"
darker-dark-color: "#666666"
background-color: "#FFFFFF"
alt-link-color: "#50E3C2"
warning-color: "#B8E986